---
title: "Serial Reversal Learning in wild nectar-feeding bats"
author: "Shambhavi"
output: html_document
fig_caption: yes
---
<style>
body {
text-align: justify}
</style>

# Results and summary figures
```{r global_options, echo=FALSE, warning=FALSE, message=FALSE, include=FALSE}
# clearing the environment
rm(list = ls())

# list of packages needed 
load.lib <- c("rmarkdown", "reshape2", "scales", "caTools", "stringr", "mgcv", "gridExtra", "tidyverse", "ggplot2", "tidyr", "lubridate", "extrafont", "extrafontdb", "brms", "bayesplot", "Hmisc", "knitr", "kableExtra")

install.lib <- load.lib[!load.lib %in% installed.packages(lib.loc = NULL)]
for (lib in install.lib) install.packages(lib, dependencies = TRUE)
sapply(load.lib, require, character = TRUE)

# set this line here
knitr::opts_knit$set(root.dir = "/srl_2017_backup_additionalfiles/Analysis/Analysis/Updated clean code")
```

```{r echo=FALSE, warning=FALSE, message=FALSE, include=FALSE}
#------------------
# Compiling of data
#------------------
# checking to see if the working directory is set correctly
setwd("/Users//shambhavi/Google Drive/Experiments & Data/srl_2017_backup_additionalfiles/Analysis/Analysis/Updated clean code")
getwd()

# preparing the data tables from the complete raw data table

# reading in the raw data 
raw_data <- read.csv2("raw_data.csv", sep = ";", header = TRUE)

# The following terms are used in the analysis of the data:
# 1. visits: each individual flower visit
# 2. trials: a group of 3 consecutive visits
# 3. block: a group of 50 trials between each reversal where one of the flowers is more rewarding
# 1 block is 50 visits

# creating a vector of the bats to be excluded from the main analysis
bats_incomp <- c("Bat7", "Bat19")

# creating a vector with the beta bats
bats_beta <- c("Bat1", "Bat2", "Bat3", "Bat4")

# creating a vector of the main experimental days
main_days <- c("Day 1", "Day 2", "Day 3")

# setting binsize and breaks for cutting up the data into block and bin
binsize <- 10
breaks <- seq(0, 3000, binsize)

# placing the visits made by the beta bats in a separate data frame

rev_learning_all_beta <- raw_data %>% 
  filter(IdLabel %in% bats_beta)

# placing the visits made on days 4, 5 and 6 in a separate data frame 

rev_learning_all_lastdays <- raw_data %>% 
  filter(!day %in% main_days)

# preparing a data frame with all the visits, including the proper but unrewarded ones 
rev_learning_all_unrew <- raw_data %>%
  filter(
    # removing the bats that did not complete the experiment
    !IdLabel %in% bats_incomp,
    !IdLabel %in% bats_beta, 
    day %in% main_days, 
    # filtering out the main experimental data
    Condition == "SerialReversalCounter"
  ) %>%
  mutate(
    # marking the difference between the normal visits in a block and the switch points
    MsgValue1 = ifelse(MsgValue1 == "switch", MsgValue1, "block"),  
    # making a column to mark the unrewarded proper visits 
      reinforce1value = replace_na(reinforce1value, 0),
      reinforce1Account = replace_na(reinforce1Account, 0), 
      Unrew = ifelse(reinforce1value != reinforce1Account, 1, 0)
  ) %>%
  rename(Bat = IdLabel) %>%
  arrange(Group, day, Bat, DateTime) %>%
  # grouping the data to count the visits, noting the reversals separately
  group_by(Bat, day) %>%
  mutate(
    # creating a column with the total number of visits made by a bat per day
    count_vis = ifelse(MsgValue1 == "switch", 0, 1), 
    count_vis = cumsum(count_vis)
  ) %>%
  # setting the maximum number of visits a night higher than the programmed max to allow for the 
  # unrewarded visits
  filter(count_vis <= 350) %>%
  ungroup()

# making a separate data frame without any unrewarded visits 
rev_learning_all <- rev_learning_all_unrew %>% 
  filter(Unrew == 0) %>%
  select(-Unrew)
  
# adding the reversal block numbers and marking the reversals for the dataset with the unrewarded visits
rev_learning_all_unrew <- rev_learning_all_unrew %>% 
  # creating a column with the reversal block number, marking the reversals
  mutate(block = ifelse(MsgValue1 == "switch", 1, 0)) %>%
  group_by(day, Bat) %>%
  mutate(block = cumsum(block)) %>%
  ungroup() %>% 
  group_by(day, Bat, block) %>%
  # creating a column with the number of visits within each block
  mutate(block_vis = ifelse(MsgValue1 == "switch", 0, 1), 
         block_vis = cumsum(block_vis), 
         # creating a new column for visits in each block to be binned
         bin = "") %>%
  ungroup() %>%
  group_by(day, Bat, block) %>%
  # cutting the visits inside each block into bin of the size set earlier
  mutate(bin = as.numeric(cut(block_vis, breaks, include.lowest = TRUE)))

# doing the same as the above step for the dataset with only the properly rewarded visits 
rev_learning_all <- rev_learning_all %>%
  # grouping the data to count the visits, noting the reversals separately
  group_by(Bat, day) %>%
  mutate(
    # noting whether the bat made a visit to the more or less rewarding flower
    reward_status = ifelse(reinforce1value > 0, 1, 0),
    # creating a column with the total number of visits made by a bat per day
    count_vis = ifelse(MsgValue1 == "switch", 0, 1), 
    count_vis = cumsum(count_vis)
  ) %>%
  # setting the maximum number of visits a night
  filter(count_vis <= 300) %>%
  ungroup() %>%
  # creating a column with the reversal block number, marking the reversals
  mutate(block = ifelse(MsgValue1 == "switch", 1, 0)) %>%
  group_by(day, Bat) %>%
  mutate(block = cumsum(block)) %>%
  ungroup() %>% 
  group_by(day, Bat, block) %>%
  # creating a column with the number of visits within each block
  mutate(block_vis = ifelse(MsgValue1 == "switch", 0, 1), 
         block_vis = cumsum(block_vis), 
  # creating a new column for visits in each block to be binned
         bin = "") %>%
  ungroup() %>%
  group_by(day, Bat, block) %>%
  # cutting the visits inside each block into bin of the size set earlier
  mutate(bin = as.numeric(cut(block_vis, breaks, include.lowest = TRUE)))


```

```{r echo=FALSE, warning=FALSE, message=FALSE, fig.align='center', fig.cap="Figure 1: All individual choices of the bats for the rewarding and non-rewarding options", fig.width = 12, fig.height = 7}
#--------------
# Summary plots
#--------------

# plot 1: plotting the individual bats' choices for the profitable option for every visit

# creating a look-up table so the reversals can be marked in the plots for the main experimental bats
rev_main <- rev_learning_ind %>%
  filter(
    MsgValue1 == "switch",
    day %in% main_days
  ) %>%
  select(day, Bat, count_vis, block, bins, MsgValue1)

rev_learning_ind %>%
  filter(day %in% main_days) %>%
  ggplot(aes(count_vis, reward_status)) +
  geom_line() +
  facet_grid(Bat ~ day) +
  geom_vline(aes(xintercept = count_vis), rev_main, colour = "red") +
  ylab("Choice for the more profitable option") +
  xlab("Visits") +
  theme_classic()
```

```{r echo=FALSE, warning=FALSE, message=FALSE, fig.align = 'center', fig.cap = "Figure 2: a) Average preferences of the bats for the rewarding option; b) Average preferences of the bats for the less rewarding option - the 'errors'", fig.width = 12, fig.height = 3}

# plot 2a: averaging the bats' preferences over day, block and bin
# creating a look-up table for the reversals

rev_main_avg <- rev_learning_avg %>%
  filter(
    reversal == "switch",
    day %in% main_days
  ) %>%
  select(day, block, day_bin, day_bin_vis)

p1 <- rev_learning_avg %>%
  # filtering only the first three main days of the experiment:
  # one group had the experiment extended a further three days
  filter(day %in% main_days) %>%
  # mutate(visits = bins * 10) %>%
  ggplot(aes(day_bin_vis, y)) +
  geom_point() +
  geom_line() +
  geom_ribbon(aes(ymin = ymin, ymax = ymax), alpha = 0.3) +
  facet_grid(. ~ day) +
  scale_x_continuous(breaks = seq(50, 300, by = 50)) +
  ylim(0, 1.05) +
  geom_hline(yintercept = c(0.25, 0.5, 0.75, 1), linetype = "dotted") +
  geom_vline(aes(xintercept = day_bin_vis), rev_main_avg, linetype = "dashed") +
  # geom_vline(xintercept = seq(50, 300, by = 50), linetype = "dashed") +
  theme_classic() +
  labs(x = "Visits", y = "Avg choice for the more profitable option ± 95% CIs") + 
  annotate(geom = "text", x = 0, y = 1.04, label = "a)", size = 3)

# plot 2b: plotting the individual bats' choices for the less profitable option, the inverse of plot 1

rev_main_err <- rev_learning_err %>%
  filter(
    reversal == "switch",
    day %in% main_days
  ) %>%
  select(day, block, day_bin, day_bin_vis)

p2 <- rev_learning_err %>%
  # filtering only the first three main days of the experiment:
  # one group had the experiment extended a further three days
  filter(day %in% main_days) %>%
  ggplot(aes(day_bin_vis, y)) +
  geom_point() +
  geom_line() +
  geom_ribbon(aes(ymin = ymin, ymax = ymax), alpha = 0.3) +
  facet_grid(. ~ day) +
  scale_x_continuous(breaks = seq(50, 300, by = 50)) +
  ylim(0, 1.05) +
  geom_hline(yintercept = c(0.25, 0.5, 0.75, 1), linetype = "dotted") +
  geom_vline(aes(xintercept = day_bin_vis), rev_main_avg, linetype = "dashed") +
  # geom_vline(xintercept = seq(50, 300, by = 50), linetype = "dashed") +
  theme_classic() +
  labs(x = "Visits", y = "Avg choice for the more profitable option ± 95% CIs") + 
  annotate(geom = "text", x = 0, y = 1.04, label = "b)", size = 4)

grid.arrange(p1, p2, ncol = 2)
```

## 2. The effect of day, block and bin on the behaviour of the bats
```{r message = FALSE, warning = FALSE, message = FALSE, echo=FALSE, results='hide'}
#--------------------------------------------------
# Fitting a Bayesian generalized linear mixed model
#--------------------------------------------------

rev_learning_stat <- rev_learning_ind %>%
  ungroup() %>%
  filter(day %in% main_days) %>%
  mutate(
    day = ifelse(day == "Day 1", 1, ifelse(day == "Day 2", 2, 3)),
    bins = bins %% 5,
    bins = ifelse(bins == 0, 5, bins)
  ) %>%
  group_by(Bat, day, block, bins) %>% 
  summarise(avg_prof = mean(reward_status))

prof <- stan_glmer(avg_prof ~ (1 | Bat) + day + block + bins + day * block + block * bins,
  data = rev_learning_stat,
  family = binomial
)

```

```{r message = FALSE, warning = FALSE, message = FALSE, echo=FALSE, results='asis'}

summary_prof <- as.data.frame(summary(prof, probs = c(0.025, 0.5, 0.975), digits = 3)) %>% 
  filter(row_number() < 7) %>% 
  select(5, 4, 6) %>% 
  rename(Estimate = 1)
kable(summary_prof, align = 'l', padding = 0, caption = 'Model summary') %>%
    kable_styling(position = "center", full_width = F)
```

# Supplementary Information 

**Table 1 - Summary of characteristics of bats that participated in the experiment**
```{r message = FALSE, warning = FALSE, message = FALSE, echo=FALSE, results='asis'}

table1 <- data.frame(
  Individual = c("Bat1", "Bat2", "Bat3", "Bat4", "Bat5", "Bat6", "Bat7", "Bat8", "Bat9", "Bat10", "Bat11", "Bat12", "Bat13", "Bat14", "Bat15", "Bat16", "Bat17", "Bat18", "Bat19", "Bat20"),
  Sex = c(rep(c("Female", "Male"), 2, each = 4), rep(c("Female"), 4)),
  Flightcage = c(rep(c(1:2), 2, each = 4), rep(c(1), 4)),
  Status = c(rep(c("Beta bat"), 4), "Completed", "Completed", "Did not complete", rep(c("Completed"), 11), "Did not complete", "Completed")
)
kable(table1, align = 'l', padding = 0) %>%
    kable_styling(position = "center", full_width = F)
```

**Figure 1 - Performance in the training stages ** 

**Figure 2 - Inter-visit intervals** 
```{r echo=FALSE, warning=FALSE, message=FALSE, fig.align='center', fig.cap="Figure 1: All individual choices of the bats for the rewarding and non-rewarding options"}
#-----------------------
# Inter-visit intervals
#-----------------------
# calculating the inter-visit intervals of all the bats 

rev_learning_ivi <- rev_learning_ind %>%
  group_by(day, Bat) %>%
  mutate(interval = as.integer(difftime(lead(DateTime), DateTime, units = "secs"))) 

rev_learning_ivi %>% 
  filter(day %in% main_days) %>% 
  ggplot(aes(interval, group = Bat)) +
  geom_density(fill = "black", color = "transparent", alpha = 0.08) +
  facet_grid(. ~ day) +
  scale_x_log10() +
  theme_bw() +
  xlab("intervisit intervals [s]") +
  scale_fill_viridis_d()
```